/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prueba;

import java.time.LocalDate;

public class App {

    public static void main(String[] args) {
        LocalDate a = LocalDate.parse(args[0]);
        LocalDate b = LocalDate.parse(args[1]);
        System.out.println(Fecha.diff(a, b));
        System.out.println(Fecha.counth(a,b));
      

    }
}
